# Proyecto 2 — Clasificación 

## Bioseñales y Sistemas
---
### Integrantes:
- Juan Camilo Basante
- Michael David Salazar
---

## Consulta — Índices EEG adicionales para clasificación en BCI

### 1. Índices EEG en sistemas BCI

La densidad espectral de potencia (PSD) es la característica más utilizada 
en sistemas BCI basados en EEG debido a su capacidad para cuantificar la 
distribución de energía en bandas de frecuencia asociadas a la actividad 
motora. Sin embargo, la literatura reporta que la PSD por sí sola presenta 
limitaciones en cuanto a precisión de clasificación, especialmente cuando 
se busca discriminar entre estados mentales similares como la imaginación 
de movimiento de mano derecha e izquierda. Por esta razón, se han propuesto 
múltiples índices complementarios que aportan información desde diferentes 
perspectivas de la señal EEG, mejorando significativamente el desempeño 
de los clasificadores.

Entre los índices más reportados en la literatura para mejorar la 
clasificación en BCI se encuentran los parámetros estadísticos en el 
dominio del tiempo, las medidas de complejidad y entropía, los índices 
de conectividad entre canales, los parámetros de Hjorth, la entropía 
espectral, la energía wavelet y la ERD/ERS relativa. Lotte et al. (2007) 
realizaron una revisión exhaustiva de algoritmos de clasificación para 
BCI basadas en EEG y concluyeron que la combinación de características 
espectrales con medidas de complejidad temporal mejora consistentemente 
la precisión de clasificación respecto al uso de la PSD sola.

---

### 2. Índices seleccionados

Se seleccionaron tres índices adicionales a la PSD por su relevancia 
demostrada en la literatura BCI, su interpretabilidad fisiológica y 
su implementabilidad directa en Python.

---

#### Índice 1 — Entropía Espectral

La entropía espectral mide el grado de irregularidad o complejidad de 
una señal EEG en el dominio de la frecuencia. Se basa en el concepto 
de entropía de Shannon aplicado a la distribución normalizada de la 
potencia espectral, interpretando la PSD como una distribución de 
probabilidad sobre las frecuencias. Un valor alto de entropía espectral 
indica que la potencia está distribuida de forma uniforme en todas las 
frecuencias (señal compleja e irregular), mientras que un valor bajo 
indica concentración de potencia en pocas frecuencias (señal más regular 
y sincronizada).

En el contexto de BCI motor, durante el reposo la señal EEG tiende a 
presentar mayor sincronización en las bandas Mu y Beta, lo que se 
traduce en menor entropía espectral. Durante la imaginación de movimiento, 
la desincronización cortical (ERD) produce una distribución más uniforme 
de la potencia, aumentando la entropía espectral. Este contraste permite 
discriminar entre el estado de reposo y los estados de imaginación de 
forma complementaria a la PSD absoluta.

**Fuente:** Inouye, T., Shinosaki, K., Sakamoto, H., Toi, S., Ukai, S., 
Iyama, A., Katsuda, Y., & Hirano, M. (1991). Quantification of EEG 
irregularity by use of the entropy of the power spectrum. 
*Electroencephalography and Clinical Neurophysiology*, 79(3), 204–210.
https://doi.org/10.1016/0013-4694(91)90138-T

---

#### Índice 2 — Parámetros de Hjorth

Los parámetros de Hjorth son tres medidas estadísticas calculadas 
directamente en el dominio del tiempo que describen propiedades 
fundamentales de la señal EEG sin necesidad de transformadas espectrales. 
Fueron propuestos por Hjorth en 1970 y se definen como:

- **Actividad:** corresponde a la varianza de la señal y representa 
  la potencia total en el dominio del tiempo.
- **Movilidad:** representa la frecuencia media de la señal, calculada 
  como la proporción entre la desviación estándar de la primera derivada 
  temporal y la desviación estándar de la señal original.
- **Complejidad:** describe la similitud de la señal con una señal 
  sinusoidal pura, calculada como la proporción entre la movilidad de 
  la primera derivada y la movilidad de la señal original.

En BCI motor, la movilidad y complejidad de la señal EEG cambian durante 
la imaginación de movimiento respecto al reposo, ya que la activación 
cortical modifica la dinámica temporal de la señal. Estos parámetros 
son computacionalmente muy eficientes y han demostrado buen desempeño 
en clasificación de estados mentales, especialmente cuando se combinan 
con características espectrales como la PSD.

**Fuente:** Hjorth, B. (1970). EEG analysis based on time domain 
properties. *Electroencephalography and Clinical Neurophysiology*, 
29(3), 306–310.
https://doi.org/10.1016/0013-4694(70)90143-4

---

#### Índice 3 — Energía Wavelet

La energía wavelet se obtiene aplicando la Transformada Wavelet Discreta 
(DWT) a la señal EEG y calculando la energía de los coeficientes de 
detalle en cada nivel de descomposición. A diferencia de la PSD, que 
ofrece una representación global de la distribución espectral, la 
energía wavelet proporciona información **tiempo-frecuencia** localizada, 
permitiendo capturar cambios transitorios en la actividad cortical 
que la PSD no puede detectar.

Cada nivel de descomposición wavelet corresponde aproximadamente a una 
banda de frecuencia del EEG. En el contexto de BCI motor, la energía 
en los niveles correspondientes a las bandas Mu (8–12 Hz) y Beta 
(13–30 Hz) refleja directamente la actividad sensoriomotora durante 
la imaginación de movimiento. Subasi y Gursoy (2010) demostraron que 
la energía wavelet combinada con clasificadores de aprendizaje automático 
supera a la PSD clásica en precisión de clasificación para tareas de 
imaginación motora, alcanzando tasas superiores al 90% en algunos sujetos.

**Fuente:** Subasi, A., & Gursoy, M. I. (2010). EEG signal classification 
using PCA, ICA, LDA and support vector machines. *Expert Systems with 
Applications*, 37(12), 8659–8666.
https://doi.org/10.1016/j.eswa.2010.06.065

---

### 3. Justificación de la selección

Los tres índices seleccionados son complementarios entre sí y con la PSD 
del proyecto 1, ya que aportan información desde diferentes dominios y 
perspectivas:

| Índice | Dominio | Información que aporta |
|--------|---------|------------------------|
| PSD (proyecto 1) | Frecuencia | Distribución de potencia por banda |
| Entropía Espectral | Frecuencia | Complejidad e irregularidad espectral |
| Parámetros de Hjorth | Tiempo | Dinámica temporal de la señal |
| Energía Wavelet | Tiempo-Frecuencia | Actividad espectral local

## Plan de análisis

### 1. Condiciones de estudio

Para este proyecto se analizan tres condiciones experimentales extraídas 
del dataset ds004362:

- **Reposo (T0):** el sujeto se encuentra en estado de reposo sin realizar 
  ninguna tarea motora ni de imaginación.
- **Imaginación de movimiento mano derecha (img_der):** el sujeto imagina 
  el movimiento de la mano derecha sin ejecutarlo físicamente.
- **Imaginación de movimiento mano izquierda (img_izq):** el sujeto imagina 
  el movimiento de la mano izquierda sin ejecutarlo físicamente.

Estas condiciones se extraen de los runs R04, R08 y R12, que corresponden 
exclusivamente a tareas de imaginación de movimiento de manos, usando los 
marcadores T0 (reposo), T1 (imaginación mano izquierda) y T2 (imaginación 
mano derecha).

---

### 2. Canales de interés

Con base en los resultados del proyecto 1, se seleccionan los canales 
que mostraron mayor discriminabilidad entre condiciones:

- **CP4** — canal con mayor estadístico en las pruebas de hipótesis 
  en ambas bandas Mu y Beta
- **C3, C4, Cz** — canales motores clásicos.
- **P4, P6, P1** — canales parietales con alta varianza entre condiciones

---

### 3. Flujo de procesamiento

Se reutiliza el pipeline de preprocesamiento del proyecto 1:

1. Carga de runs R04, R08 y R12 por sujeto
2. Filtrado pasa-banda (1–40 Hz) + Notch (60 Hz)
3. Re-referenciación por promedio común (CAR)
4. Segmentación en épocas (-1 a +4 segundos por evento)
5. Exclusión de canales contaminados (AF7, Fp1, AF3, AF8, Fp2, Fpz, Iz, O2, PO8)

---

### 4. Extracción de características

Para cada época, canal de interés y condición se calculan los siguientes 
índices:

| Índice | Descripción | Bandas/Parámetros |
|--------|-------------|-------------------|
| PSD | Densidad espectral de potencia (Welch) | Delta, Theta, Mu, Beta, Gamma |
| Entropía Espectral | Complejidad espectral de la señal | Banda Mu y Beta |
| Parámetros de Hjorth | Actividad, Movilidad y Complejidad | Dominio del tiempo |
| Energía Wavelet | Energía por nivel de descomposición DWT | Niveles correspondientes a Mu y Beta |

Todos los índices se almacenan en un DataFrame estructurado con columnas 
para sujeto, condición, canal e índice calculado.

---

### 5. Análisis estadístico

El análisis estadístico sigue el mismo esquema del proyecto 1:

**Estadística descriptiva:**
- Boxplots y violin plots por índice, canal y condición
- Identificación visual de qué índices y canales muestran mayor 
  separación entre las tres condiciones

**Pruebas de hipótesis:**
- Shapiro-Wilk para verificar normalidad
- ANOVA o Kruskal-Wallis según resultado de normalidad
- Post-hoc de Tukey o Dunn para identificar qué pares de condiciones 
  difieren significativamente

---

### 6. Clasificación

Con los índices que muestren mayor diferencia entre condiciones se 
construyen clasificadores usando:

- **Estrategia de entrenamiento:** K-fold cross validation (k=5)
- **Clasificadores:** tres arquitecturas de red neuronal, SVM y XGBoost
- **Evaluación:** matrices de confusión y métricas de desempeño 
  (accuracy, precision, recall, F1-score)

---

### 7. Hipótesis

**Hipótesis 1 — Diferencia entre reposo e imaginación:**
- H₀: No existe diferencia en los índices EEG entre el reposo y las 
  condiciones de imaginación de movimiento.
- H₁: Al menos un índice presenta diferencias significativas entre 
  el reposo y las condiciones de imaginación.

**Hipótesis 2 — Diferencia entre imaginación derecha e izquierda:**
- H₀: No existe diferencia en los índices EEG entre la imaginación 
  de mano derecha e imaginación de mano izquierda.
- H₁: Al menos un índice presenta diferencias significativas entre 
  la imaginación de mano derecha e izquierda, evidenciando 
  lateralización hemisférica.


---

## Programación

### 1. Función de extracción de características

Se construye una función que recibe las épocas preprocesadas y calcula,
para cada canal de interés y condición, los siguientes índices:

- **Densidad Espectral de Potencia (PSD):** potencia por banda de frecuencia
  mediante el método de Welch.
- **Entropía Espectral:** complejidad espectral de la señal en las bandas
  Mu y Beta.
- **Parámetros de Hjorth:** actividad, movilidad y complejidad en el
  dominio del tiempo.
- **Energía Wavelet:** energía por nivel de descomposición DWT en los
  niveles correspondientes a las bandas Mu y Beta.

In [17]:
import os
import re
import mne
import pywt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from mne.io import read_raw_edf
from scipy.signal import welch
from scipy.stats import entropy

In [18]:
#configuración general

RUTA_DATOS      = os.path.join(os.getcwd(), "datos", "files")
RUNS_INTERES    = ['R04', 'R08', 'R12']  # Solo imaginación
CANALES_INTERES = ['C3', 'C4', 'Cz', 'CP4', 'P4', 'P6', 'P1']
CANALES_EXCLUIR = ['AF7', 'Fp1', 'AF3', 'AF8', 'Fp2', 'Fpz',
                   'Iz', 'O2', 'PO8']
SUJETOS         = [f"S{i:03d}" for i in range(1, 110)]

BANDAS = {
    'Delta': (1,  4),
    'Theta': (4,  8),
    'Mu':    (8,  12),
    'Beta':  (13, 30),
    'Gamma': (30, 40)
}

# ============================================================
# LISTAR ARCHIVOS
# ============================================================

def run_exacto(ruta, runs):
    nombre = os.path.basename(ruta)
    return any(re.search(rf'{run}\.edf$', nombre) for run in runs)

archivos = []
for root, dirs, files in os.walk(RUTA_DATOS):
    for file in files:
        if file.endswith(".edf"):
            archivos.append(os.path.join(root, file))

archivos_validos = [a for a in archivos
                    if run_exacto(a, RUNS_INTERES)
                    and any(s in os.path.basename(a) for s in SUJETOS)]
archivos_validos.sort()
print(f"Archivos encontrados: {len(archivos_validos)}")

# ============================================================
# CARGAR SUJETO
# ============================================================

def cargar_sujeto(archivos, sujeto):
    """
    Carga y concatena todos los runs de interés de un sujeto,
    etiquetando correctamente cada condición.
    """
    runs_sujeto = sorted([a for a in archivos 
                          if sujeto in os.path.basename(a)])

    print(f"\nSujeto {sujeto}: {len(runs_sujeto)} runs encontrados")

    raws = []
    for ruta in runs_sujeto:
        nombre   = os.path.basename(ruta)
        raw_temp = read_raw_edf(ruta, preload=True, verbose=False)
        mne.datasets.eegbci.standardize(raw_temp)
        raw_temp.set_montage('standard_1005')

        # Solo imaginación → T1=img_izq, T2=img_der
        mapping = {'T0': 'reposo', 'T1': 'img_izq', 'T2': 'img_der'}
        raw_temp.annotations.rename(mapping)
        raws.append(raw_temp)

    raw = mne.concatenate_raws(raws, verbose=False)

    # Limpiar boundaries
    raw.annotations.delete(
        [i for i, desc in enumerate(raw.annotations.description)
         if 'boundary' in desc.lower()]
    )

    print(f"  Señal concatenada: {raw.times[-1]:.1f} segundos")
    print(f"  Anotaciones: {len(raw.annotations)}")
    return raw

# ============================================================
# PREPROCESAMIENTO
# ============================================================

def preprocesar_eeg(raw, visualizar=False):
    """
    Aplica el flujo de preprocesamiento sobre todos los canales.
    """
    raw_original = raw.copy()

    # FASE 1
    print("=" * 50)
    print("FASE 1: Señal cruda")
    if visualizar:
        raw_original.plot(duration=30, title='Fase 1 — Señal cruda',
                          scalings='auto')
        plt.show()

    # FASE 2
    print("=" * 50)
    print("FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)")
    raw.filter(1, 40, verbose=False)
    raw.notch_filter(60, verbose=False)

    if visualizar:
        raw.plot(duration=30, title='Fase 2 — Filtrado',
                 scalings='auto')
        plt.show()

    # FASE 3
    print("=" * 50)
    print("FASE 3: Re-referenciación CAR")
    raw.set_eeg_reference('average', projection=False, verbose=False)

    if visualizar:
        raw.plot(duration=30, title='Fase 3 — CAR', scalings='auto')
        plt.show()

    # FASE 4
    print("=" * 50)
    print("FASE 4: Segmentación basada en eventos")
    eventos, id_eventos = mne.events_from_annotations(raw, verbose=False)
    print(f"  Eventos encontrados: {len(eventos)}")
    print(f"  Condiciones: {id_eventos}")

    # FASE 5
    print("=" * 50)
    print("FASE 5: Épocas")
    canales_picks = mne.pick_types(raw.info, eeg=True,
                                   exclude=CANALES_EXCLUIR)
    epochs = mne.Epochs(
        raw,
        eventos,
        event_id=id_eventos,
        tmin=-1,
        tmax=4,
        picks=canales_picks,
        baseline=(-1, 0),
        reject=None,
        preload=True,
        verbose=False
    )

    print(f"  Épocas totales: {len(epochs)}")
    for cond in epochs.event_id:
        print(f"    {cond}: {len(epochs[cond])}")

    if visualizar:
        epochs.plot(n_epochs=5, title='Fase 5 — Épocas',
                    scalings=dict(eeg=20e-6))
        plt.show()

    return epochs

Archivos encontrados: 327

### 1.1 Funciones de cálculo de índices

In [19]:
def calcular_entropia_espectral(signal, fs, band=(8, 30)):
    """
    Calcula la entropía espectral de una señal en una banda de frecuencia.
    
    Parámetros:
        signal (np.array): señal 1D
        fs (float): frecuencia de muestreo
        band (tuple): rango de frecuencia (fmin, fmax)
    
    Retorna:
        float: entropía espectral
    """
    freqs, psd = welch(signal, fs=fs, nperseg=int(fs * 2))
    idx        = np.logical_and(freqs >= band[0], freqs <= band[1])
    psd_band   = psd[idx]
    psd_norm   = psd_band / psd_band.sum()
    return entropy(psd_norm, base=2)


def calcular_hjorth(signal):
    """
    Calcula los parámetros de Hjorth de una señal.
    
    Parámetros:
        signal (np.array): señal 1D
    
    Retorna:
        tuple: (actividad, movilidad, complejidad)
    """
    actividad  = np.var(signal)
    d1         = np.diff(signal)
    movilidad  = np.std(d1) / np.std(signal)
    d2         = np.diff(d1)
    complejidad = (np.std(d2) / np.std(d1)) / movilidad
    return actividad, movilidad, complejidad


def calcular_energia_wavelet(signal, wavelet='db4', nivel=4):
    """
    Calcula la energía de los coeficientes wavelet por nivel.
    
    Parámetros:
        signal (np.array): señal 1D
        wavelet (str): tipo de wavelet (default: db4)
        nivel (int): niveles de descomposición
    
    Retorna:
        dict: energía por nivel de descomposición
    """
    coeficientes = pywt.wavedec(signal, wavelet, level=nivel)
    energias     = {}
    for i, coef in enumerate(coeficientes):
        energias[f'wavelet_nivel_{i}'] = np.sum(coef ** 2)
    return energias


def calcular_psd_bandas(signal, fs):
    """
    Calcula la potencia por banda de frecuencia usando Welch.
    
    Parámetros:
        signal (np.array): señal 1D
        fs (float): frecuencia de muestreo
    
    Retorna:
        dict: potencia por banda
    """
    freqs, psd = welch(signal, fs=fs, nperseg=int(fs * 2))
    potencias  = {}
    for banda, (fmin, fmax) in BANDAS.items():
        idx = np.logical_and(freqs >= fmin, freqs <= fmax)
        potencias[f'psd_{banda}'] = np.mean(psd[idx])
    return potencias

### 1.2 Función principal de extracción de características

Se integran todos los índices en una sola función que recibe las épocas preprocesadas y retorna un diccionario con todas las características calculadas para cada época, canal y condición.

In [20]:
def extraer_caracteristicas(epochs, canales=CANALES_INTERES):
    """
    Extrae todos los índices EEG para cada época y canal de interés.
    
    Parámetros:
        epochs (mne.Epochs): épocas preprocesadas
        canales (list): canales de interés
    
    Retorna:
        list: lista de diccionarios con características por época
    """
    fs          = epochs.info['sfreq']
    registros   = []

    for condicion in epochs.event_id:
        data = epochs[condicion].get_data(picks=canales)
        # data shape: (épocas, canales, muestras)

        for epoca_idx in range(data.shape[0]):
            for canal_idx, canal in enumerate(canales):
                señal = data[epoca_idx, canal_idx, :]

                fila = {
                    'condicion': condicion,
                    'canal':     canal,
                    'epoca':     epoca_idx
                }

                # PSD por bandas
                fila.update(calcular_psd_bandas(señal, fs))

                # Entropía espectral en Mu y Beta
                fila['entropia_mu']   = calcular_entropia_espectral(
                    señal, fs, band=(8, 12))
                fila['entropia_beta'] = calcular_entropia_espectral(
                    señal, fs, band=(13, 30))

                # Parámetros de Hjorth
                act, mov, comp = calcular_hjorth(señal)
                fila['hjorth_actividad']   = act
                fila['hjorth_movilidad']   = mov
                fila['hjorth_complejidad'] = comp

                # Energía Wavelet
                fila.update(calcular_energia_wavelet(señal))

                registros.append(fila)

    return registros

### 1.3 Prueba con un sujeto

Se prueba la función de extracción de características sobre el sujeto
S001 para verificar que todos los índices se calculan correctamente
antes de aplicar la rutina sobre todos los sujetos.

In [21]:
# Reutilizar funciones del proyecto 1
# cargar_sujeto() y preprocesar_eeg() ya están definidas

# Cargar y preprocesar S001
raw_s001    = cargar_sujeto(archivos_validos, sujeto='S001')
epochs_s001 = preprocesar_eeg(raw_s001, visualizar=False)

# Extraer características
registros_s001 = extraer_caracteristicas(epochs_s001)
df_s001        = pd.DataFrame(registros_s001)

print(f"Características extraídas para S001:")
print(f"  Filas:    {len(df_s001)}")
print(f"  Columnas: {list(df_s001.columns)}")
df_s001.head()

Sujeto S001: 3 runs encontrados
  Señal concatenada: 375.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44
Características extraídas para S001:
  Filas:    623
  Columnas: ['condicion', 'canal', 'epoca', 'psd_Delta', 'psd_Theta', 'psd_Mu', 'psd_Beta', 'psd_Gamma', 'entropia_mu', 'entropia_beta', 'hjorth_actividad', 'hjorth_movilidad', 'hjorth_complejidad', 'wavelet_nivel_0', 'wavelet_nivel_1', 'wavelet_nivel_2', 'wavelet_nivel_3', 'wavelet_nivel_4']

,condicion,canal,epoca,psd_Delta,psd_Theta,psd_Mu,psd_Beta,psd_Gamma,entropia_mu,entropia_beta,hjorth_actividad,hjorth_movilidad,hjorth_complejidad,wavelet_nivel_0,wavelet_nivel_1,wavelet_nivel_2,wavelet_nivel_3,wavelet_nivel_4
0,img_der,C3,0,1.818045e-11,9.117268e-12,4.415398e-12,2.328174e-12,1.762701e-12,3.056652,4.984094,2.105743e-10,0.610487,1.922258,9.065189e-08,3.075959e-08,2.027729e-08,2.642733e-08,1.209240e-08
1,img_der,C4,0,2.509593e-11,7.149488e-12,6.877437e-12,2.507766e-12,1.169284e-12,3.027038,4.968915,2.662872e-10,0.480149,2.294727,1.374717e-07,2.246410e-08,2.949651e-08,2.615676e-08,5.551812e-09
2,img_der,Cz,0,3.027739e-11,9.421118e-12,6.908929e-12,1.855552e-12,1.310531e-12,3.104959,4.977057,2.778308e-10,0.470565,2.320940,1.287387e-07,4.059661e-08,3.486181e-08,2.180313e-08,6.089124e-09
3,img_der,CP4,0,2.918800e-11,6.914820e-12,7.601085e-12,2.192822e-12,8.972870e-13,3.039999,4.726617,2.221703e-10,0.449716,2.336547,1.481198e-07,1.825713e-08,3.128501e-08,1.841501e-08,3.829061e-09
4,img_der,P4,0,5.585577e-11,1.084521e-11,9.942767e-12,3.565249e-12,2.086198e-12,3.124816,4.837895,3.820976e-10,0.488485,2.269555,2.834975e-07,3.251985e-08,5.577172e-08,3.207054e-08,9.364746e-09


---

### 2. Rutina general — Todos los sujetos

Se aplica el flujo completo sobre los 109 sujetos del dataset y se
almacenan todos los resultados en un DataFrame estructurado. Dado que
este proceso puede tomar varias horas, el resultado se guarda en un
archivo CSV para evitar reprocesar en ejecuciones futuras.

In [ ]:
def procesar_todos_sujetos(archivos_validos, sujetos, visualizar=False):
    """
    Aplica el flujo completo sobre todos los sujetos y retorna un DataFrame
    con todos los índices calculados por época, canal y condición.
    
    Parámetros:
        archivos_validos (list): Lista de rutas de archivos EDF
        sujetos (list): Lista de sujetos a procesar
        visualizar (bool): Si True, grafica las fases de preprocesamiento
    
    Retorna:
        pd.DataFrame: DataFrame con todos los índices
    """
    registros = []

    for sujeto in sujetos:
        print(f"\n{'='*50}")
        print(f"Procesando {sujeto}...")
        print(f"{'='*50}")

        try:
            raw       = cargar_sujeto(archivos_validos, sujeto)
            epochs    = preprocesar_eeg(raw, visualizar=visualizar)
            resultado = extraer_caracteristicas(epochs)

            for fila in resultado:
                fila['sujeto'] = sujeto

            registros.extend(resultado)

        except Exception as e:
            print(f"  !!!!!  Error procesando {sujeto}: {e}")
            continue

    df = pd.DataFrame(registros)

    # Reordenar columnas
    cols_inicio = ['sujeto', 'condicion', 'canal', 'epoca']
    cols_resto  = [c for c in df.columns if c not in cols_inicio]
    df = df[cols_inicio + cols_resto]

    # Label encoding
    label_mapping = {'reposo': 0, 'img_der': 1, 'img_izq': 2} #Etiquetado de condiciones
    df['label']   = df['condicion'].map(label_mapping)

    # Guardar CSV
    df.to_csv('caracteristicas_proyecto2.csv', index=False)
    print("\n  DataFrame guardado en caracteristicas_proyecto2.csv")

    return df

# Ejecutar rutina completa
df_caracteristicas = procesar_todos_sujetos(
    archivos_validos,
    SUJETOS,
    visualizar=False
)

print(f"\nDataFrame generado exitosamente:")
print(f"  Filas totales:  {len(df_caracteristicas)}")
print(f"  Columnas:       {list(df_caracteristicas.columns)}")
print(f"  Sujetos:        {df_caracteristicas['sujeto'].nunique()}")
print(f"  Condiciones:    {df_caracteristicas['condicion'].unique()}")
print(f"  Canales:        {df_caracteristicas['canal'].unique()}")
df_caracteristicas.head()

==================================================
Procesando S001...
==================================================

Sujeto S001: 3 runs encontrados
  Señal concatenada: 375.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S002...
==================================================

Sujeto S002: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S003...
==================================================

Sujeto S003: 3 runs encontrados
  Señal concatenada: 375.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S004...
==================================================

Sujeto S004: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S005...
==================================================

Sujeto S005: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 24
    img_izq: 21
    reposo: 44

==================================================
Procesando S006...
==================================================

Sujeto S006: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 21
    img_izq: 24
    reposo: 44

==================================================
Procesando S007...
==================================================

Sujeto S007: 3 runs encontrados
  Señal concatenada: 375.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S008...
==================================================

Sujeto S008: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S009...
==================================================

Sujeto S009: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 21
    img_izq: 24
    reposo: 44

==================================================
Procesando S010...
==================================================

Sujeto S010: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 21
    img_izq: 24
    reposo: 44

==================================================
Procesando S011...
==================================================

Sujeto S011: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S012...
==================================================

Sujeto S012: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 24
    img_izq: 21
    reposo: 44

==================================================
Procesando S013...
==================================================

Sujeto S013: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S014...
==================================================

Sujeto S014: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S015...
==================================================

Sujeto S015: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S016...
==================================================

Sujeto S016: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S017...
==================================================

Sujeto S017: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S018...
==================================================

Sujeto S018: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S019...
==================================================

Sujeto S019: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S020...
==================================================

Sujeto S020: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S021...
==================================================

Sujeto S021: 3 runs encontrados
  Señal concatenada: 375.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 21
    img_izq: 24
    reposo: 44

==================================================
Procesando S022...
==================================================

Sujeto S022: 3 runs encontrados
  Señal concatenada: 375.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S023...
==================================================

Sujeto S023: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S024...
==================================================

Sujeto S024: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S025...
==================================================

Sujeto S025: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S026...
==================================================

Sujeto S026: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================

C:\Users\basan\AppData\Local\Temp\ipykernel_24484\182069076.py:55: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw_temp = read_raw_edf(ruta, preload=True, verbose=False)
C:\Users\basan\AppData\Local\Temp\ipykernel_24484\182069076.py:55: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw_temp = read_raw_edf(ruta, preload=True, verbose=False)
C:\Users\basan\AppData\Local\Temp\ipykernel_24484\182069076.py:55: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw_temp = read_raw_edf(ruta, preload=True, verbose=False)

  Señal concatenada: 369.0 segundos
  Anotaciones: 72
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 72
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 71
    img_der: 18
    img_izq: 18
    reposo: 35

==================================================
Procesando S101...
==================================================

Sujeto S101: 3 runs encontrados
  Señal concatenada: 375.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S102...
==================================================

Sujeto S102: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 88
    img_der: 23
    img_izq: 21
    reposo: 44

==================================================
Procesando S103...
==================================================

Sujeto S103: 3 runs encontrados
  Señal concatenada: 375.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S104...
==================================================

Sujeto S104: 3 runs encontrados
  Señal concatenada: 352.0 segundos
  Anotaciones: 86
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 86
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 85
    img_der: 21
    img_izq: 22
    reposo: 42

==================================================
Procesando S105...
==================================================

Sujeto S105: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

==================================================
Procesando S106...
==================================================

Sujeto S106: 3 runs encontrados
  Señal concatenada: 375.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 21
    img_izq: 24
    reposo: 44

==================================================
Procesando S107...
==================================================

Sujeto S107: 3 runs encontrados
  Señal concatenada: 375.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 21
    img_izq: 24
    reposo: 44

==================================================
Procesando S108...
==================================================

Sujeto S108: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 23
    img_izq: 22
    reposo: 44

==================================================
Procesando S109...
==================================================

Sujeto S109: 3 runs encontrados
  Señal concatenada: 369.0 segundos
  Anotaciones: 90
==================================================
FASE 1: Señal cruda
==================================================
FASE 2: Filtrado (1–40 Hz) + Notch (60 Hz)
==================================================
FASE 3: Re-referenciación CAR
==================================================
FASE 4: Segmentación basada en eventos
  Eventos encontrados: 90
  Condiciones: {np.str_('img_der'): 1, np.str_('img_izq'): 2, np.str_('reposo'): 3}
==================================================
FASE 5: Épocas
  Épocas totales: 89
    img_der: 22
    img_izq: 23
    reposo: 44

  DataFrame guardado en caracteristicas_proyecto2.csv

DataFrame generado exitosamente:
  Filas totales:  68040
  Columnas:       ['sujeto', 'condicion', 'canal', 'epoca', 'psd_Delta', 'psd_Theta', 'psd_Mu', 'psd_Beta', 'psd_Gamma', 'entropia_mu', 'entropia_beta', 'hjorth_actividad', 'hjorth_movilidad', 'hjorth_complejidad', 'wavelet_nivel_0', 'wavelet_nivel_1', 'wavelet_nivel_2', 'wavelet_nivel_3', 'wavelet_nivel_4', 'label']
  Sujetos:        109
  Condiciones:    <StringArray>
['img_der', 'img_izq', 'reposo']
Length: 3, dtype: str
  Canales:        <StringArray>
['C3', 'C4', 'Cz', 'CP4', 'P4', 'P6', 'P1']
Length: 7, dtype: str

,sujeto,condicion,canal,epoca,psd_Delta,psd_Theta,psd_Mu,psd_Beta,psd_Gamma,entropia_mu,entropia_beta,hjorth_actividad,hjorth_movilidad,hjorth_complejidad,wavelet_nivel_0,wavelet_nivel_1,wavelet_nivel_2,wavelet_nivel_3,wavelet_nivel_4,label
0,S001,img_der,C3,0,1.818045e-11,9.117268e-12,4.415398e-12,2.328174e-12,1.762701e-12,3.056652,4.984094,2.105743e-10,0.610487,1.922258,9.065189e-08,3.075959e-08,2.027729e-08,2.642733e-08,1.209240e-08,1
1,S001,img_der,C4,0,2.509593e-11,7.149488e-12,6.877437e-12,2.507766e-12,1.169284e-12,3.027038,4.968915,2.662872e-10,0.480149,2.294727,1.374717e-07,2.246410e-08,2.949651e-08,2.615676e-08,5.551812e-09,1
2,S001,img_der,Cz,0,3.027739e-11,9.421118e-12,6.908929e-12,1.855552e-12,1.310531e-12,3.104959,4.977057,2.778308e-10,0.470565,2.320940,1.287387e-07,4.059661e-08,3.486181e-08,2.180313e-08,6.089124e-09,1
3,S001,img_der,CP4,0,2.918800e-11,6.914820e-12,7.601085e-12,2.192822e-12,8.972870e-13,3.039999,4.726617,2.221703e-10,0.449716,2.336547,1.481198e-07,1.825713e-08,3.128501e-08,1.841501e-08,3.829061e-09,1
4,S001,img_der,P4,0,5.585577e-11,1.084521e-11,9.942767e-12,3.565249e-12,2.086198e-12,3.124816,4.837895,3.820976e-10,0.488485,2.269555,2.834975e-07,3.251985e-08,5.577172e-08,3.207054e-08,9.364746e-09,1